name: Build run passwall file

on:
  repository_dispatch:
  push:
    branches: [ main]
  workflow_dispatch:

jobs:
  build-openwrt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
      
    - name: Build run files
      uses: sirpdboy/buildrun@openclash
      with:
        OUTPUT_DIR: "./pkgrun"
        
    - name: Set tag name
      run: |
          TODAY=$(date -u -d '+8 hour' +'%Y-%m-%d')
          echo "tag_name=$TODAY" >> $GITHUB_ENV

    - name: Upload run files as release assets
      uses: softprops/action-gh-release@v2.1.0
      with:
          tag_name: ${{ env.tag_name }}
          name: "Build - ${{ env.tag_name }}"
          files: ./pkgrun/*.run
          
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
             <p align="left">
              <img src="https://img.shields.io/github/downloads/loso3000/ota-go/${{ env.tag_name }}/total?style=for-the-badge&label=%E4%BB%8A%E6%97%A5%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&labelColor=427e25&color=black"/>
             </p>
          draft: false
          prerelease: false
          
